title: Shaped by the Oath

description: >-
  Sistema de RPG de horror pessoal ambientado em um cenário noir-punk,
  focado em expressão de personagens, consequências narrativas e investigação.

url: "https://Gam13.github.io"
baseurl: "/Shaped-by-the-Oath---Engine"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Navegação
search_enabled: true

# Rodapé
footer_content: "Shaped by the Oath"

# GitHub
github_username: Gam13

# Aparência
color_scheme: dark

# Permalinks amigáveis
permalink: pretty
